//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crouny.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int RuleId { get; set; }
        public System.Guid DeviceId { get; set; }
        public int PluginId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Settings { get; set; }
        public string State { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Plugin Plugin { get; set; }
    }
}
